- name: Install tap for hashicorp
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install Ansible for configuration management
  ansible.builtin.pip:
    name: ansible
    executable: pipx
    extra_args: --include-deps

- name: Update .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ANSIBLE"
    mode: "0644"
    block: |
      export PATH="$HOME/.local/bin:$PATH"

- name: Install Ansible linting tool
  ansible.builtin.pip:
    name: ansible-lint
    executable: pipx

- name: Install Vagrant for managing development environments
  community.general.homebrew_cask:
    name: vagrant

- name: Install Google Cloud SDK
  community.general.homebrew_cask:
    name: google-cloud-sdk

- name: Install Terraform for resource management
  community.general.homebrew:
    name: hashicorp/tap/terraform

- name: Install Packer for building multiple artifacts from configuration management
  community.general.homebrew:
    name: hashicorp/tap/packer

- name: Install templates for Kubernetes manifests
  community.general.homebrew:
    name: ktmpl

- name: Install Kuberenetes command line
  community.general.homebrew:
    name: kubernetes-cli

- name: Install vault
  community.general.homebrew:
    name: hashicorp/tap/vault

- name: Install kustomize
  community.general.homebrew:
    name: kustomize
