---
- name: Play for setting up my-macos-setup
  hosts: all

  pre_tasks:

    - name: Get brew path
      ansible.builtin.command: brew --prefix
      register: brew_path

    - name: Add brew to shell
      ansible.builtin.blockinfile:
        create: true
        path: ~/.zprofile
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR BREW"
        mode: "0644"
        block: |
          eval "$({{ brew_path.stdout_lines[0] }}/bin/brew shellenv)"

    - name: Add /usr/local/sbin to path
      ansible.builtin.lineinfile:
        path: /etc/paths
        line: '/usr/local/sbin'
        insertbefore: '/usr/sbin'
      become: true

    - name: Update hostname
      ansible.builtin.hostname:
        name: "{{ ansible_user_id }}-mac"
      become: true

  roles:

    - source-control
    - docker
    - cli-tools
    - python
    - system
    - gradle
    - node
    - golang
    - flutter
    - office
    - plantuml
    - semgrep
    - security
    - internet
    - infrastructure-as-code
    - media

  post_tasks:

    - name: Change .local ownership and permissions
      ansible.builtin.file:
        path: "{{ brew_path.stdout_lines[0] }}/share owner={{ ansible_user_id }}"
        recurse: true
        mode: '0755'
      become: true
