- name: Install nmap for network discovery and security auditing
  community.general.homebrew:
    name: nmap

- name: Install nikto web server scanner
  community.general.homebrew:
    name: nikto

- name: Install slowhttptest denial of service attack tool
  community.general.homebrew:
    name: slowhttptest
