- name: Install IntelliJ IDE
  community.general.homebrew_cask:
    name: intellij-idea-ce

- name: Install Cocoapods dependency manager
  ansible.builtin.command: brew install cocoapods

- name: Install 1Password password manager
  community.general.homebrew_cask:
    name: 1password

- name: Install TablePlus database management tool
  community.general.homebrew_cask:
    name: tableplus

- name: Install psql client
  community.general.homebrew:
    name: libpq

- name: Get psql client path
  ansible.builtin.command: brew --prefix libpq
  register: psql_client_path

- name: Add psql to bin
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PSQL"
    mode: "0644"
    block: |
      export PATH="{{ psql_client_path.stdout_lines[0] }}/bin:$PATH"

- name: Install miro collaboration whiteboard
  community.general.homebrew_cask:
    name: miro

- name: Install Alfred productivity utility
  community.general.homebrew_cask:
    name: alfred

- name: Install The Unarchiver
  community.general.homebrew_cask:
    name: the-unarchiver

- name: Install App Cleaner
  community.general.homebrew_cask:
    name: appcleaner

- name: Install flycut clipboard manager
  community.general.homebrew_cask:
    name: flycut

- name: Install clocker timezone menu
  community.general.homebrew_cask:
    name: clocker

- name: Install Google Drive
  community.general.homebrew_cask:
    name: google-drive

- name: Install Wireshark packet analyzer
  community.general.homebrew_cask:
    name: wireshark

- name: Install loom for screen recording
  community.general.homebrew_cask:
    name: loom

- name: Install notion
  community.general.homebrew_cask:
    name: notion
