- name: Add pip3 as pip to .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PYTHON"
    mode: "0644"
    block: |
      alias pip=pip3
      alias python=python3

- name: Install python
  community.general.homebrew:
    name: python@3.11

- name: Install pipx
  community.general.homebrew:
    name: pipx

- name: Install python setuptools
  ansible.builtin.pip:
    name: setuptools

- name: Install PyCharm IDE
  community.general.homebrew_cask:
    name: pycharm
