- name: Install flutter
  community.general.homebrew_cask:
    name: flutter

- name: Precache
  ansible.builtin.command: flutter precache

- name: Install lcov for code coverage
  community.general.homebrew:
    name: lcov
