- name: Install ferdium for aggregating messaging platforms
  community.general.homebrew_cask:
    name: ferdium

- name: Install zoom for internet telephony
  community.general.homebrew_cask:
    name: zoom

- name: Install Chrome browser
  community.general.homebrew_cask:
    name: google-chrome

- name: Install Brave browser
  community.general.homebrew_cask:
    name: brave-browser
